apiVersion: v1
description: 'stash-mariadb - MariaDB database plugin for Stash by AppsCode'
name: stash-mariadb
version: v2020.09.16
appVersion: v2020.09.16
home: https://stash.run
icon: https://cdn.appscode.com/images/products/stash/addons/mariadb-stash-addon.png
sources:
- https://github.com/stashed/mariadb
maintainers:
- name: appscode
  email: support@appscode.com
