project:
  name: stash-mariadb
  shortName: stash-mariadb
  url: https://github.com/stashed/mariadb
  description: "MariaDB database backup/restore plugin for [Stash by AppsCode](https://stash.run)"
  app: "necessary `Function` and `Task` definition to backup or restore MariaDB 10.5.5
    using Stash"
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: stash-mariadb
  version: v2020.09.16
  values: "-- generate from values file --"
  valuesExample: "-- generate from values file --"
prerequisites:
- Kubernetes 1.11+
release:
  name: stash-mariadb-v2020.09.16
  namespace: kube-system
